### ISSUE TITLE
PIP feature on Chrome

### ISSUE THREAD

**Issue by Elettrotecnica** [polimediaupv/paella-player#2]
Dear maintainers,

on your homepage https://paellaplayer.upv.es/ it appears to me as if the PIP feature does not work in Chrome/Chromium. On Firefox and Edge, I can detach one of the streams and move the little window around as expected.

This is also our experience on the Paella Player version we integrate on our website.

Any idea of why this could be the case?

Many thanks in advance

Antonio

**Comment by ferserc1** [comment]
Paella does not implement any PIP feature. The feature you are referring to is implemented by the developers of the browser, and therefore we have nothing to do with it.

https://support.mozilla.org/en-US/kb/about-picture-picture-firefox

https://techdows.com/2021/09/microsoft-edge-video-picture-in-picture-button.html
